### ISSUE TITLE
[Jenkins] Remote call on JNLP4-connect connection failed

### ISSUE THREAD

**Issue by huyle-anh** [huyle-anh/workspace#1]
Describe the bug:

- Error call on JNLP4-connect connection failed

Steps:

- Run a Jenkins job by pipeline 
- Observe the result 

Expected:

- No errors occur

The log message shows when error 

```
Robot results publisher started...
-Parsing output xml:
Failed!
java.io.IOException: Remote call on JNLP4-connect connection from 10.38.xx.xx/10.38.xx.xx:42152 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at hudson.FilePath.act(FilePath.java:1192)
	at hudson.FilePath.act(FilePath.java:1181)
	at hudson.plugins.robot.RobotParser.parse(RobotParser.java:48)
	at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:246)
	at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:267)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at java.xml/javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:366)
	at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:309)
	at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:222)
	at java.xml/javax.xml.stream.XMLInputFactory.newInstance(XMLInputFactory.java:161)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:83)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:52)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.38.152.230/10.38.152.230:42152
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1192)
		at hudson.FilePath.act(FilePath.java:1181)
		at hudson.plugins.robot.RobotParser.parse(RobotParser.java:48)
		at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:246)
		at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:267)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at java.xml/javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:363)
	... 15 more
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Error accessing configuration file
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1173)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1206)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.xml/javax.xml.stream.FactoryFinder$1.run(FactoryFinder.java:348)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.xml/javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:337)
	... 15 more
Caused by: java.nio.file.NoSuchFileException: /ampere/jenkins/remoting/jarCache/86/579386AA9CF144ADFB99CA32E347BB.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1414)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:840)
	at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:866)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:855)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:257)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1165)
	... 23 more
[Pipeline] echo
Start making components for email report.
```

**Comment by huyle-anh** [comment]
Something has conflicted in Jenkin's plugin installation packages. The restart Jenkins service, the error has now disappeared.

> `
> sudo systemctl restart jenkins
> `

Some information from: https://stackoverflow.com/questions/52207248/jenkins-jnlp4-connect-connection-from-xxx-xxx-xxx-xxx-failed-after-the-success-o

**Comment by huyle-anh** [comment]
Restarting the Jenkins service fixes this problem.
